const foodNames = [
  "artichok", 
  "arugula", 
  "asparagu", 
  "aubergin", 
  "amaranth", 
  "legum", 
  "alfalfa sprout", 
  "azuki bean", 
  "bean sprout", 
  "black bean", 
  "black eye pea", 
  "black-ey pea", 
  "borlotti bean", 
  "broad bean", 
  "chickpea", 
  "garbanzo", 
  "ceci bean", 
  "green bean", 
  "kidney bean", 
  "lentil", 
  "lima bean", 
  "butter bean", 
  "mung bean", 
  "navi bean", 
  "pinto bean", 
  "runner bean", 
  "split pea", 
  "soy bean", 
  "pea", 
  "mangetout", 
  "snap pea", 
  "beet green", 
  "bok choy", 
  "broccoflow", 
  "broccoli", 
  "brussel sprout", 
  "cabbag", 
  "calabres", 
  "carrot", 
  "cauliflow", 
  "celeri", 
  "chard", 
  "collard green", 
  "corn salad", 
  "endiv", 
  "fiddlehead", 
  "frise", 
  "fennel", 
  "anis", 
  "basil", 
  "caraway", 
  "cilantro seed", 
  "coriand", 
  "chamomil", 
  "sprouts",
  "moong sprouts",
  "moong beans",
  "dill", 
  "fennel", 
  "lavend", 
  "lemon grass", 
  "marjoram", 
  "oregano", 
  "parsley", 
  "rosemari", 
  "sage", 
  "thyme", 
  "kale", 
  "kohlrabi", 
  "lettuc lactuca sativa", 
  "maiz", 
  "mushroom", 
  "mustard green", 
  "nettl", 
  "new zealand spinach", 
  "okra", 
  "chive", 
  "garlic", 
  "leek allium porrum", 
  "onion", 
  "shallot", 
  "spring onion", 
  "parsley", 
  "pepp", 
  "green pepp", 
  "red pepp", 
  "bell pepp", 
  "pimento", 
  "chili pepp", 
  "jalapeño", 
  "habanero", 
  "paprika", 
  "tabasco pepp", 
  "cayenn pepp", 
  "radicchio", 
  "rhubarb", 
  "root veget", 
  "beetroot", 
  "carrot", 
  "celeriac", 
  "daikon", 
  "ginger", 
  "parsnip", 
  "rutabaga", 
  "turnip", 
  "radish", 
  "swede", 
  "turnip", 
  "wasabi", 
  "horseradish", 
  "white radish", 
  "salsifi", 
  "skirret", 
  "spinach", 
  "topinambur", 
  "squash", 
  "acorn squash", 
  "butternut squash", 
  "banana squash", 
  "courgett", 
  "cucumb", 
  "delicata", 
  "gem squash", 
  "hubbard squash", 
  "marrow", 
  "patti pan", 
  "pumpkin", 
  "spaghetti squash", 
  "tat soi", 
  "tomato", 
  "tuber", 
  "jicama", 
  "jerusalem artichok", 
  "potato", 
  "sunchok", 
  "sweet potato", 
  "taro", 
  "yam", 
  "turnip green", 
  "water chestnut", 
  "watercress", 
  "zucchini", 
  "appl", 
  "apricot", 
  "avocado", 
  "banana", 
  "blackcurr", 
  "currant", 
  "cherimoya", 
  "coconut", 
  "cucumb", 
  "custard appl", 
  "damson", 
  "date", 
  "dragonfruit", 
  "durian", 
  "feijoa", 
  "fig", 
  "grape", 
  "raisin", 
  "grapefruit", 
  "guava", 
  "jabuticaba", 
  "jackfruit", 
  "jambul", 
  "jujub", 
  "kiwifruit", 
  "kumquat", 
  "lemon", 
  "lime", 
  "loquat", 
  "longan", 
  "lyche", 
  "mango", 
  "melon", 
  "cantaloup", 
  "honeydew", 
  "watermelon", 
  "miracl fruit", 
  "nectarin", 
  "nanc", 
  "oliv", 
  "orang", 
  "blood orang", 
  "clementin", 
  "mandarin", 
  "tangerin", 
  "papaya", 
  "passionfruit", 
  "peach", 
  "pear", 
  "persimmon", 
  "physali", 
  "plantain", 
  "plum", 
  "prune", 
  "dri plum", 
  "pineappl", 
  "plumcot", 
  "pluot", 
  "pomegran", 
  "pomelo", 
  "purpl mangosteen", 
  "quinc", 
  "bilberri", 
  "blackberri", 
  "blueberri", 
  "cherri", 
  "cranberri", 
  "cloudberri", 
  "elderberri", 
  "goji berri", 
  "gooseberri", 
  "boysenberri", 
  "honeyberri", 
  "huckleberri", 
  "junip berri", 
  "marionberri", 
  "mulberri", 
  "raspberri", 
  "salmonberri", 
  "strawberri", 
  "salal berri", 
  "bilberri", 
  "blackberri", 
  "blueberri", 
  "cherri", 
  "cranberri", 
  "cloudberri", 
  "elderberri", 
  "goji berri", 
  "gooseberri", 
  "boysenberri", 
  "honeyberri", 
  "huckleberri", 
  "junip berri", 
  "marionberri", 
  "mulberri", 
  "raspberri", 
  "salmonberri", 
  "strawberri", 
  "salal berri", 
  "rambutan", 
  "redcurr", 
  "salak", 
  "satsuma", 
  "soursop", 
  "star fruit", 
  "solanum quitoens", 
  "tamarillo", 
  "tamarind", 
  "ugli fruit", 
  "yuzu",
  "appl",
  "apricot",
  "avocado",
  "banana",
  "bilberri",
  "blackberri",
  "blackcurr",
  "blueberri",
  "boysenberri",
  "currant",
  "cherri",
  "cherimoya",
  "cloudberri",
  "coconut",
  "cranberri",
  "cucumb",
  "custard appl",
  "damson",
  "date",
  "dragonfruit",
  "durian",
  "elderberri",
  "feijoa",
  "fig",
  "goji berri",
  "gooseberri",
  "grape",
  "raisin",
  "grapefruit",
  "guava",
  "honeyberri",
  "huckleberri",
  "jabuticaba",
  "jackfruit",
  "jambul",
  "jujub",
  "juniper berri",
  "kiwifruit",
  "kumquat",
  "lemon",
  "lime",
  "loquat",
  "longan",
  "lyche",
  "mango",
  "marionberri",
  "melon",
  "cantaloup",
  "honeydew",
  "watermelon",
  "miracle fruit",
  "mulberri",
  "nectarin",
  "nanc",
  "oliv",
  "orang",
  "blood orang",
  "clementin",
  "mandarin",
  "tangerin",
  "papaya",
  "passionfruit",
  "peach",
  "pear",
  "persimmon",
  "physali",
  "plantain",
  "plum",
  "prune",
  "pineappl",
  "plumcot",
  "pomegran",
  "pomelo",
  "purple mangosteen",
  "quinc",
  "raspberri",
  "salmonberri",
  "rambutan",
  "redcurr",
  "salal berri",
  "salak",
  "satsuma",
  "soursop",
  "star fruit",
  "solanum quitoens",
  "strawberri",
  "tamarillo",
  "tamarind",
  "ugli fruit",
  "yuzu",
  "avocado",
  "chili pepp",
  "corn kernel",
  "cucumb",
  "eggplant",
  "oliv",
  "pea",
  "squash",
  "sunflower se",
  "tomato",
  "artichok",
  "arugula",
  "asparagu",
  "aubergin",
  "amaranth",
  "legum",
  "alfalfa sprout",
  "azuki bean",
  "bean sprout",
  "black bean",
  "black-eyed pea",
  "borlotti bean",
  "broad bean",
  "chickpea",
  "garbanzo",
  "ceci bean",
  "green bean",
  "kidney bean",
  "lentil",
  "lima bean",
  "butter bean",
  "mung bean",
  "navy bean",
  "pinto bean",
  "runner bean",
  "split pea",
  "soy bean",
  "pea",
  "mangetout",
  "snap pea",
  "beet green",
  "bok choi",
  "broccoflow",
  "broccoli",
  "brussels sprout",
  "cabbag",
  "calabres",
  "carrot",
  "cauliflow",
  "celeri",
  "chard",
  "collard green",
  "corn salad",
  "endiv",
  "fiddlehead",
  "frise",
  "fennel",
  "herbs and spic",
  "anis",
  "basil",
  "carawai",
  "cilantro se",
  "coriand",
  "chamomil",
  "dill",
  "fennel",
  "lavend",
  "lemon grass",
  "marjoram",
  "oregano",
  "parslei",
  "rosemari",
  "sage",
  "thyme",
  "kale",
  "kohlrabi",
  "lettuc",
  "maiz",
  "mushroom",
  "mustard green",
  "nettl",
  "new zealand spinach",
  "okra",
  "onion famili",
  "chive",
  "garlic",
  "leek allium porrum",
  "onion",
  "shallot",
  "spring onion",
  "parslei",
  "pepper",
  "green pepp",
  "red pepp",
  "chili pepp",
  "jalapeño",
  "habanero",
  "paprika",
  "tabasco pepp",
  "cayenne pepp",
  "radicchio",
  "rhubarb",
  "root veget",
  "beetroot",
  "mangel",
  "carrot",
  "celeriac",
  "daikon",
  "ginger",
  "parsnip",
  "rutabaga",
  "turnip",
  "radish",
  "swede",
  "turnip",
  "wasabi",
  "horseradish",
  "white radish",
  "salsifi",
  "skirret",
  "spinach",
  "topinambur",
  "squash",
  "acorn squash",
  "butternut squash",
  "banana squash",
  "courgett",
  "cucumb",
  "delicata",
  "gem squash",
  "hubbard squash",
  "marrow",
  "patty pan",
  "pumpkin",
  "spaghetti squash",
  "tat soi",
  "tomato",
  "tuber",
  "jicama",
  "jerusalem artichok",
  "potato",
  "sunchok",
  "sweet potato",
  "taro",
  "yam",
  "turnip green",
  "water chestnut",
  "watercress",
  "zucchini",
  "bear",
  "beef",
  "beef heart",
  "beef liv",
  "beef tongu",
  "bone soup",
  "buffalo, bison",
  "calf liv",
  "carib",
  "goat",
  "ham",
  "hors",
  "kangaroo",
  "lamb",
  "marrow soup",
  "moos",
  "mutton",
  "opossum",
  "organ meat",
  "pork",
  "pork, bacon",
  "rabbit",
  "snake",
  "squirrel",
  "sweetbread",
  "tripe",
  "turtl",
  "veal",
  "venison",
  "chicken",
  "chicken liv",
  "cornish game hen",
  "duck",
  "duck liv",
  "emu",
  "gizzard",
  "goos",
  "goose liv",
  "grous",
  "guinea hen",
  "liver",
  "organ",
  "ostrich",
  "partridg",
  "pheasant",
  "quail",
  "squab",
  "turkei",
  "abalon",
  "sea-ear",
  "muttonshel",
  "anchovi",
  "barracuda",
  "bass",
  "bluefish",
  "bullhead",
  "butterfish",
  "carp",
  "catfish",
  "chub",
  "clam",
  "cod",
  "conch",
  "crab",
  "croaker",
  "cusk",
  "drum",
  "eel",
  "flounder",
  "frog",
  "gray sol",
  "grouper",
  "haddock",
  "hake",
  "halfmoon fish",
  "halibut",
  "harvest fish",
  "her",
  "jellyfish",
  "lobster",
  "mackerel",
  "mahi-mahi",
  "monkfish",
  "mullet",
  "muskellung",
  "mussel",
  "ocean pout",
  "octopu",
  "opaley",
  "orange roughi",
  "oyster",
  "parrotfish",
  "perch",
  "pickerel",
  "walley",
  "pike",
  "pilchard",
  "pollock",
  "pompano",
  "porgi",
  "red snapp",
  "rosefish",
  "salmon",
  "salmon",
  "sardin",
  "scallop",
  "scrod",
  "scup",
  "sea beam",
  "shad",
  "shark",
  "sheepshead fish",
  "shrimp",
  "skate",
  "smelt",
  "snail",
  "sole",
  "squid",
  "sturgeon",
  "sucker",
  "sunfish, pumpkinse",
  "swordfish",
  "tilapia",
  "tilefish",
  "rainbow trout",
  "trout",
  "tuna",
  "turbot",
  "turtl",
  "weakfish",
  "whitefish",
  "white",
  "wolfish, atlant",
  "yellowtail",
  "abondance fermlere herve mon",
  "american chees",
  "appenzel",
  "bergenost",
  "blue chees",
  "borough market stilton",
  "brick chees",
  "brie chees",
  "butter",
  "cabot",
  "cahill’s port",
  "camembert chees",
  "campode montalban",
  "casein",
  "cheddar chees",
  "cheshire chees",
  "colby chees",
  "colby-jack chees",
  "cordob",
  "cottage chees",
  "cougar gold cheddar",
  "cream chees",
  "cup chees",
  "drunken goat chees",
  "dubling",
  "edam chees",
  "emmenthal, swiss chees",
  "english derby with sag",
  "farmer chees",
  "feta chees",
  "fiscalim sand joaquin",
  "ghee",
  "goat chees",
  "gorgonzola chees",
  "gouda chees",
  "government chees",
  "gran queso",
  "gruyere chees",
  "half & half",
  "havarti chees",
  "herve mons pave de nord",
  "herve mons tomme des bois noir",
  "jack, monterei",
  "jarlsberg chees",
  "kefalotyri chees",
  "kefir",
  "kerrygold invernia",
  "le gruye’re switzerland",
  "liederkranz chees",
  "limburger chees",
  "manchego",
  "manchego chees",
  "mascarpone chees",
  "buttermilk",
  "gota milk",
  "buffalo milk",
  "mimolett",
  "montasio",
  "monterey jack chees",
  "mozzarella chees",
  "muenster chees",
  "naked goat",
  "neufchatel chees",
  "paneer chees",
  "parmesan chees",
  "pastore sini",
  "pecorino chees",
  "pepperjack chees",
  "pimento chees",
  "pinconning chees",
  "plave",
  "port de salut chees",
  "provel chees",
  "provolone chees",
  "quark chees",
  "ricotta chees",
  "romanian urda",
  "romano chees",
  "roquefort chees",
  "salad dressings, creami",
  "sheep milk chees",
  "sour cream",
  "spray chees",
  "stilton chees",
  "string chees",
  "swiss chees",
  "teleme chees",
  "tete de moin",
  "ubriaco del plave po-si",
  "uniekaas reserv",
  "uniekaas robusto",
  "velveeta",
  "whey protein powd",
  "white chees",
  "yellow chees",
  "plain yogurt",
  "yogurt",
  "greek yogurt"
]

exports.getNatural = function(name) {
  const stemmer = require('porter-stemmer').stemmer
  const sname = stemmer(name)
  console.log('stemmed word', sname)
  return foodNames.indexOf(sname)
}
